version: '3.8'

services:
  db:
    image: postgres:15
    container_name: study4you-db
    restart: always
    environment:
      POSTGRES_USER: study4you_user
      POSTGRES_PASSWORD: "1012004"
      POSTGRES_DB: study4you
      TZ: "Asia/Ho_Chi_Minh" # Thêm dòng này
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: study4you-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@study4you.com
      PGADMIN_DEFAULT_PASSWORD: admin
      TZ: "Asia/Ho_Chi_Minh" # Thêm dòng này
    ports:
      - "1234:80"
    depends_on:
      - db

volumes:
  postgres_data: